### ISSUE TITLE
Require newline after comma

### ISSUE THREAD

**Issue by fifn2** [primer/stylelint-config-primer#21]
I think this style guide should require a newline after commas in value lists. For example,
This would be flagged:
```css
.dp-4 {
  box-shadow:  0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.2);
}
```
But this wouldn't:
```css
.dp-4 {
  box-shadow:
    0 4px 5px 0 rgba(0, 0, 0, 0.14),
    0 1px 10px 0 rgba(0, 0, 0, 0.12),
    0 2px 4px -1px rgba(0, 0, 0, 0.2);
}
```
This can be done by putting this in your stylelint config:
```
"rules": {
   "value-list-comma-newline-after": "always"
 },
```
I figure that if you do this for selectors, you should do this for value lists.
